replicaCount: 1

image:
  repository: kanukhosla10/artemis-simple-app
  pullPolicy: IfNotPresent
  tag: "sha-test"

podAnnotations: {}

service:
  name: simple-app
  type: ClusterIP
  containerPort: 80

env:
  # appVersion: sha-test
  environment: "dev"


httpRoute:
  hostnames:
    - "dev.artemis.simple-app.654537853.xyz"

resources: {}
