replicaCount: 1
image:
  repository: kanukhosla10/artemis-simple-app
  pullPolicy: IfNotPresent
  tag: "sha-19346b3"
podAnnotations: {}
service:
  name: simple-app
  type: ClusterIP
  containerPort: 80
env:
  # appVersion: sha-test
  environment: "staging"
httpRoute:
  hostnames:
  - "staging.artemis.simple-app.654537853.xyz"
resources: {}
