apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-simple-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis-simple-app-test
  template:
    metadata:
      labels:
        app: artemis-simple-app-test
    spec:
      containers:
        - name: app
          image: kanukhosla10/artemis-simple-app:sha-19346b3
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "sha-test"
            - name: APP_ENV
              value: "dev"